### ISSUE TITLE
Ana variable

### ISSUE THREAD

**Issue by benjibenoit** [nowfloats/ProjectAna#10]
Hello.

I got a problem, I have a GetText where the constumer need to put his name. After that, I want to write it. How can I write the variable of his name ?

regards,
Thx

**Comment by NizamLZ** [comment]
Hi,

To do that, in the node where you added GetText type of button, go to Node Info tab and enter the variable name of your choice in the variable name field. (ex: person_name)

Now in the following nodes, wherever you want to display that variable's value, use {{person_name}}. In this case, it will be replaced by the name entered by the user.

**Comment by benjibenoit** [comment]
Awesome !! thx

**Comment by alimobh** [comment]
It didn't, at least in the simulator. @NizamLZ
