### ISSUE TITLE
Download location

### ISSUE THREAD

**Issue by probonopd** [nowfloats/ProjectAna#14]
https://github.com/Kitsune-tools/ProjectAna/blob/2644ab811f5c906431a1e024813d11082e1bc624/deploy.sh#L9-L14

Where can the AppImage be downloaded from? Please publish the download URLs, thanks.

**Comment by NizamLZ** [comment]
Its specified in the readme.

Download The Ana app from https://www.ana.chat/downloads.html

**Comment by probonopd** [comment]
Thank you very much, I must have overlooked it. Would it be possible to have a permalink that would always redirect to the latest version of the AppImage, e.g., https://cdn.ana.chat/dist/ana-app/linux-ia32/ana-conversation-studio-latest-x86_64.AppImage would redirect to https://cdn.ana.chat/dist/ana-app/linux-ia32/ana-conversation-studio-0.1.8-x86_64.AppImage?
