### ISSUE TITLE
Any button with a "get[something]" node.

### ISSUE THREAD

**Issue by benjibenoit** [nowfloats/ProjectAna#17]
Hi,

I'm trying to put an other button with a getImage or get... but I can't. When I put both, the get is not shown. How can I do to display both nodes ?

Regards,
shankiflang

**Comment by NizamLZ** [comment]
Hello,

It is a limitation in Ana platform. You can have multiple buttons of type NextNode/OpenUrl but other than those, there can only be one input button. 

Will keep you posted about the updates to the platform regarding this.

**Comment by benjibenoit** [comment]
Hi,

I understand that but I just need to be able to cancel if the customer don't want to share something. How can I make it ?

**Comment by NizamLZ** [comment]
In a node, ask the user if he wants to enter the address or skip and then take him to the node in which get address button is present.

**Comment by benjibenoit** [comment]
Ok thank :'(
