### ISSUE TITLE
ANA App - Unable to copy existing node

### ISSUE THREAD

**Issue by rajakarunanidi** [nowfloats/ProjectAna#19]
Hi All,

I am unable to copy existing Node in ANA App.. I tried both Stable (0.1.8) and Beta (0.1.8-beta.13) 
 windows versions.. Same issue persist.
Note: I downloaded both versions from https://www.ana.chat/downloads.html

This fix will help to reduce effort and time..

**Comment by rajakarunanidi** [comment]
Hi @NizamLZ , @Rajeshrash,
Is this bug or something i am doing wrongly..

**Comment by Rajeshrash** [comment]
Hi @rajakarunanidi 

I am Rajesh from Ana team please make a single click on the node and press 'c' to copy the node. let me know if the issue still persists.

**Comment by rajakarunanidi** [comment]
Thanks @Rajeshrash.. You are savior of my effort & time..

Can you help me on this as well.. Please...  https://github.com/Kitsune-tools/ANAChat-Web/issues/3#issuecomment-420159966
