### ISSUE TITLE
Developer Certificate expired

### ISSUE THREAD

**Issue by rajakarunanidi** [nowfloats/ProjectAna#20]
Hi All,
On installing ANA.Conversation.Studio.Setup.5.0.4.msi, while trying to use simulator its throwing below error

Error: The developer certificate "C:\Users\\AppData\Local\Temp\ANA-82a53105-cdfa-41b6-ab42-96a9f593ca58\ANAConversationSimulator_3.0.2.0_x86_Debug.cer" has expired. One possible cause is the system clock isn't set to the correct date and time. If the system settings are correct, contact the app owner to re-create a package or bundle with a valid certificate.

How to open existing chat project ### (developed using Ana App for Windows - v0.1.8-beta.13) in ANA.Conversation.Studio.5.0.4? Its throwing error as null value..

**Comment by NizamLZ** [comment]
You might be using the legecy simulator. When using Ana app for windows, simulator comes with it. You just have to hit run in the chat flow designer of The Ana app. Additional installation of the simulator is not needed anymore.

Chat flows designed in The Ana app are not supported in the old Ana Conversation Studio.

**Comment by rajakarunanidi** [comment]
Ok.. So ANA conversation Studio are legacy versions and Ana App for Windows - v0.1.8-beta.13 is latest version.. Is i am right?

**Comment by NizamLZ** [comment]
Yes

**Comment by rajakarunanidi** [comment]
Ok.. In this case, few features available in ANAConversionStudio are not in v0.1.8-beta.13 .. eg.. Repeat on in GetItemFromSource, is Hidden, default options on text, etc..

**Comment by NizamLZ** [comment]
New chatbot architecture is much more scalable and has a lot of optimisations. In course of the development few features had to be dropped off.
