### ISSUE TITLE
Ana Documentation

### ISSUE THREAD

**Issue by orion-pax** [nowfloats/ProjectAna#8]
Where can I get the documentation/comprehensive tutorial or primer for using Ana?

**Comment by menneni** [comment]
Please refer following doc for setting up ANA server https://github.com/Kitsune-tools/ProjectANA/blob/master/ANA-CHAT-SERVER-SETUP-README.MD and refer following doc for web chat plugin https://github.com/Kitsune-tools/ANAChat-Web.

We are working on creating comprehensive video tutorial, it will be available very soon.

**Comment by orion-pax** [comment]
That's great, thanks for the info, will check out the links out soon.

**Comment by amigliora** [comment]
I have everything connected but when I tried to publish my bot, the Ana is asking me for a business account and I couldn’t find in the existing read me files where to get the business account, could you please help?

**Comment by amigliora** [comment]
Disregard my comment I found it :)
Thanks
