### ISSUE TITLE
Using a Collection/List to dynamically populate a node's Carousel items

### ISSUE THREAD

**Issue by orion-pax** [nowfloats/ProjectAna#9]
Hello,
Let me start by commending you on the awesome work on the Carousel feature. However,
I am of the opinion that it would be a great idea to add functionality which facilitates dynamic creation and subsequent addition of carousel items using data from a list/collection. Maybe I haven't discovered the option yet, but if it already exists kindly assist me on how this can be achieved.

For instance, if an api call from a previous node returns a json object with information as shown in the attached image below, one may want to generate carousel items using the list if one is not aware or expects a lot of items which in this case renders manual creation a very tedious process to say the least. 
![screenshot from 2018-05-31 04-14-21](https://user-images.githubusercontent.com/19870545/40757905-12dc0d16-648b-11e8-852c-eeb41ba46b98.png)

**Comment by NizamLZ** [comment]
Hello Orion Pax,

Thank you for using Ana. We absolutely understand the need for dynamic carousel items and buttons. The feature is on the roadmap and can be expected in the next big release. 

Meanwhile, there is a hack with one limitation and a bit of an effort. 
The limitation is, you need to decide on the maximum number of carousel items you want to display. Let's say 5 at a time. You need to create 5 nodes, with the first node having the carousel with 1 carousel item, the second node having the carousel with 2 carousel items and so on until 5.

Then you can introduce a condition node on top of all these carousels, based on the response items count, chat can go to respective node and the carousel will be rendered.

I would also like to invite you to fork and submit a pull request if you can which supports this dynamic repeat feature. https://github.com/Kitsune-tools/ana-bot-core is the repo where changes have to be made.

**Comment by orion-pax** [comment]
Hi NizamLZ,

Thanks for the response and brilliant idea. Will definitely check that out. Also thanks much for the invite, will look into it.

**Comment by NizamLZ** [comment]
This feature is now available in Ana App v0.1.8-beta.13 . Download the sample flow from below link which will help you understand how to use it.  
[ana-repeat-feature-demo](https://cdn.ana.chat/demo-chatflows/ana-repeat-feature-demo.anaproj )
